ALTER TABLE AchievementType
ADD PRIMARY KEY (Id)

ALTER TABLE Course
ADD PRIMARY KEY (Id)

ALTER TABLE Grade
ADD PRIMARY KEY (Id)

ALTER TABLE GradeDetails
ADD PRIMARY KEY (Id)

ALTER TABLE Student
ADD PRIMARY KEY (Id)

ALTER TABLE Teacher
ADD PRIMARY KEY (Id)